import "./globals.css";
import Navigation from "./components/navigation";

import { Geist } from 'next/font/google';

const geist = Geist({
  subsets: ['latin'],
  weight: ['400', '500','600','700', '800'], // Specify font weights needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
      className={geist.className}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
