import "./globals.css";
import Navigation from "./components/navigation";

import { Inter } from 'next/font/google';

const interFont = Inter({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify font weights needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={interFont.className}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
